#!/bin/bash

SOURCE_DIR="./code"


BINARY_DIR="./binary"

mkdir -p "$BINARY_DIR"
for file in "$SOURCE_DIR"/*.c; do
    filename=$(basename -- "$file")
    base_name="${filename%.*}"
    tcc "$file" -o "$BINARY_DIR/$base_name"
    if [ $? -eq 0 ]; then
        echo "Compiled $file successfully."
    else
        echo "Failed to compile $file."
    fi
done

echo "All files processed."
